// [snowpack] add styles to the page (skip if no document exists)
if (typeof document !== 'undefined') {
  const code = "@-webkit-keyframes shake {\n    0%,\n    100% {\n        -webkit-transform: translateX(0);\n        transform: translateX(0);\n    }\n    10%,\n    30%,\n    50%,\n    70% {\n        -webkit-transform: translateX(-10px);\n        transform: translateX(-10px);\n    }\n    20%,\n    40% {\n        -webkit-transform: translateX(10px);\n        transform: translateX(10px);\n    }\n    60% {\n        -webkit-transform: translateX(8px);\n        transform: translateX(8px);\n    }\n    80% {\n        -webkit-transform: translateX(6px);\n        transform: translateX(6px);\n    }\n    90% {\n        -webkit-transform: translateX(-6px);\n        transform: translateX(-6px);\n    }\n}\n\n@keyframes shake {\n    0%,\n    100% {\n        -webkit-transform: translateX(0);\n        transform: translateX(0);\n    }\n    10%,\n    30%,\n    50%,\n    70% {\n        -webkit-transform: translateX(-10px);\n        transform: translateX(-10px);\n    }\n    20%,\n    40% {\n        -webkit-transform: translateX(10px);\n        transform: translateX(10px);\n    }\n    60% {\n        -webkit-transform: translateX(8px);\n        transform: translateX(8px);\n    }\n    80% {\n        -webkit-transform: translateX(6px);\n        transform: translateX(6px);\n    }\n    90% {\n        -webkit-transform: translateX(-6px);\n        transform: translateX(-6px);\n    }\n}\n\n.file__label {\n    display: flex;\n    width: 300px;\n    height: 250px;\n    flex-direction: column;\n    justify-content: center;\n    align-items: center;\n    border: 5px dashed #000;\n    border-radius: 5px;\n    cursor: pointer;\n}\n\n.file__label.invalid {\n    border-color: #dc3545;\n    color: #dc3545;\n    -webkit-animation: shake 1s ease-in-out both;\n    animation: shake 1s ease-in-out both;\n}\n\n.file__label > div {\n    margin-top: 10px;\n}\n";

  const styleEl = document.createElement("style");
  const codeEl = document.createTextNode(code);
  styleEl.type = 'text/css';
  styleEl.appendChild(codeEl);
  document.head.appendChild(styleEl);
}