// [snowpack] add styles to the page (skip if no document exists)
if (typeof document !== 'undefined') {
  const code = ".option__resize {\n    position: absolute;\n    top: 0;\n    right: 0;\n    bottom: 0;\n    left: 0;\n    border: 3px solid;\n}\n\n.option__resize__move {\n    position: absolute;\n    top: 10px;\n    right: 10px;\n    bottom: 10px;\n    left: 10px;\n    cursor: move;\n}\n\n.optin__resize__point {\n    position: absolute;\n    width: 20px;\n    height: 20px;\n    background: rgba(0, 0, 0, 0.5);\n    border-radius: 50%;\n    box-sizing: border-box;\n    transform: scale(0.5);\n    transition: transform 0.25s ease-in-out;\n}\n\n.optin__resize__point:hover {\n    transform: scale(1);\n}\n\n.option__resize__point--top--left {\n    top: -11.5px;\n    left: -11.5px;\n    cursor: nwse-resize;\n}\n.option__resize__point--top--center {\n    top: -11.5px;\n    left: calc(50% - 11.5px);\n    cursor: ns-resize;\n}\n\n.option__resize__point--top--right {\n    top: -11.5px;\n    right: -11.5px;\n    cursor: nesw-resize;\n}\n\n.option__resize__point--center--left {\n    top: calc(50% - 11.5px);\n    left: -11.5px;\n    cursor: ew-resize;\n}\n\n.option__resize__point--center--right {\n    top: calc(50% - 11.5px);\n    right: -11.5px;\n    cursor: ew-resize;\n}\n\n.option__resize__point--bottom--left {\n    bottom: -11.5px;\n    left: -11.5px;\n    cursor: nesw-resize;\n}\n\n.option__resize__point--bottom--center {\n    bottom: -11.5px;\n    left: calc(50% - 11.5px);\n    cursor: ns-resize;\n}\n\n.option__resize__point--bottom--right {\n    bottom: -11.5px;\n    right: -11.5px;\n    cursor: nwse-resize;\n}\n";

  const styleEl = document.createElement("style");
  const codeEl = document.createTextNode(code);
  styleEl.type = 'text/css';
  styleEl.appendChild(codeEl);
  document.head.appendChild(styleEl);
}